
import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./navbar";
import SideBar from "./sidebar";
import SubNav from "./subNav";
import { Provider } from "react-redux";
import { store } from "../lib/store";
import AppWrapper from "./appWrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="violet">
          <div className="h-screen">
            <main className="h-screen w-full bg-[#FBFBFB] ">
              <AppWrapper childrenProp={children}/>
              {/* <Provider store={store}>
                <div className="h-screen w-full">
                  <NavBar />
                  <div className="flex h-[90%]">
                    <SideBar />
                    <div className="w-full md:w-[80%]">
                      <SubNav />
                      {children}
                    </div>
                  </div>
                </div>
              </Provider> */}
              {/* <ThemePanel /> */}
            </main>
          </div>
        </Theme>
      </body>
    </html>
  );
}
